#!/bin/bash

TOPIC=${TOPIC:?A topic is required}

./local-kafka
local/kafka/bin/kafka-topics.sh --create \
 --zookeeper localhost:2181 \
 --replication-factor 1 \
 --partitions 1 \
 --topic "${TOPIC}"

